# Generated by Django 3.2.14 on 2022-08-22 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='current_occupancy',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='game_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='gameroom',
            name='max_members',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
